import Head from 'next/head'
import Hero from "@/components/Hero";
import Strip from '@/components/Strip';
import Body from '@/components/Body';

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Strip />
        <Body />
        <img src="/img/home/4.jpg" width="100%" />
      </main>
    </>
  )
}
